accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordChangeView

from .views import RegistrationView, UserUpdateView, LoginView

urlpatterns = [
    path('signin/', RegistrationView.as_view(), name='signin'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('update/password/', PasswordChangeView.as_view(
        template_name='accounts/password_change.html',
        success_url=reverse_lazy('index')
    ), name='password_change'),
]

chat/urls.py
from django.urls import path
from rest_framework import routers

from .views import IndexView, ChatRoomListCreateAPIView, ChatRoomAPIView, join_room_api_view, leave_room_api_view,\
    get_user_list

router = routers.SimpleRouter()

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('api/chat/', ChatRoomListCreateAPIView.as_view(), name='list_create'),
    path('api/chat/<int:pk>/', ChatRoomAPIView.as_view(), name='chat_room'),
    path('api/chat/<int:pk>/join/', join_room_api_view, name='join_chat_room'),
    path('api/chat/<int:pk>/leave/', leave_room_api_view, name='leave_chat_room'),
    path('api/chat/<int:pk>/users/', get_user_list, name='user_list'),
]

django_chat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include('chat.urls'), name='chat'),
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .manager import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()

    login = models.CharField(
        _("login"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    name = models.CharField(
        _("name"),
        max_length=150,
        help_text=_(
            "150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
        blank=True,
    )
    avatar = models.ImageField(upload_to='avatars/', blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'login'

chat/models.py
from django.db import models

from django.contrib.auth import get_user_model


UserModel = get_user_model()


class ChatRoom(models.Model):
    name = models.CharField(max_length=150, unique=True)
    owner = models.ForeignKey(UserModel, on_delete=models.PROTECT)
    users = models.ManyToManyField(UserModel, blank=True, related_name='chat_rooms')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.users.add(self.owner)


class Client(models.Model):
    channel_name = models.CharField(max_length=50, primary_key=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms

from .models import User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('login', 'name')
        field_classes = {"login": UsernameField}


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'avatar')

accounts/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import login

from .forms import UserRegistrationForm, UserUpdateForm
from .models import User


class RegistrationView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/registration.html'
    success_url = '/'

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.object = request.user
            return redirect(self.get_success_url())

        return super().get(request, *args, **kwargs)


class LoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = '/'
    next_page = '/'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(self.get_success_url())

        return super().get(request, *args, **kwargs)


class UserUpdateView(UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/update.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return self.request.user

chat/views.py
from django.contrib.auth import get_user_model
from django.db.models import F
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics, status
from rest_framework.decorators import api_view
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from .models import ChatRoom, Client
from .serializers import ChatRoomSerializer
from .permissions import IsOwnerOrReadOnly


User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'chat/index.html'
    login_url = 'accounts:login'


class ChatRoomListCreateAPIView(generics.ListCreateAPIView):
    queryset = ChatRoom.objects.all()
    serializer_class = ChatRoomSerializer

    def get_queryset(self):
        queryset = super().get_queryset()

        if 'my' in self.request.query_params:
            queryset = queryset.filter(users=self.request.user)
        elif 'all' not in self.request.query_params:
            queryset = queryset.exclude(users=self.request.user)

        return queryset


class ChatRoomAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = ChatRoom.objects.all()
    serializer_class = ChatRoomSerializer
    permission_classes = (IsOwnerOrReadOnly, )


@api_view(['POST'])
def join_room_api_view(request, pk: int):
    chat_room = get_object_or_404(ChatRoom.objects.all(), pk=pk)
    chat_room.users.add(request.user)
    return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['POST'])
def leave_room_api_view(request, pk: int):
    chat_room = get_object_or_404(ChatRoom.objects.all(), pk=pk)

    if chat_room.owner == request.user:
        return Response({"message": "You can't leave the room you own."}, status=status.HTTP_403_FORBIDDEN)

    chat_room.users.remove(request.user)
    return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET'])
def get_user_list(request, pk: int):
    channel_layer = get_channel_layer()
    channels = set(channel_layer.groups.get(f"room_{pk}", {}))
    users = list(User.objects.filter(client__channel_name__in=channels)
                 .values('id', 'name', 'avatar'))

    return Response(users, status=status.HTTP_200_OK)

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Log In</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Log In</button>
  <p>or <a href="{% url 'accounts:signin' %}">Sign in</a></p>
</form>
</body>
</html>

templates/accounts/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Log Out</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<div>
  <p>Вы вышли.</p>
  <p>
    <a href="{% url 'accounts:login' %}">Войти</a>
    <a href="{% url 'accounts:signin' %}">Регистрация</a>
  </p>
</div>
</body>
</html>

templates/accounts/password_change.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Смена пароля</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Изменить</button>
</form>
</body>
</html>

templates/accounts/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Sign In</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign In</button>
  <p>or <a href="{% url 'accounts:login' %}">Log in</a></p>
</form>
</body>
</html>

templates/accounts/update.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>User Settings</title>
  <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Изменить</button>
  <p>
    <a href="{% url 'accounts:password_change' %}">Сменить пароль</a>
    <a href="{% url 'accounts:logout' %}">Выйти</a>
  </p>
</form>
</body>
</html>

templates/chat/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<aside>
  <div id="chat-rooms">
    <a id="roomssetings">Chats:</a>
    <ul id="siderooms"></ul>
  </div>
  <div id="user">
    <a href="{% url 'accounts:update' %}">
      <img class="avatar" src="{% firstof request.user.avatar 'static/images/noavatar.png' %}">
      {{ request.user }}
    </a>
  </div>
</aside>
<main>
</main>
<script>
  const csrfToken="{{ csrf_token }}"
  const userInfo={
    id: {{ request.user.id }},
    name: "{{ request.user.name }}",
    avatar: "{{ request.user.avatar }}"
  }
</script>
<script src="{% static 'js/apps.js' %}"></script>
<script src="{% static 'js/websocket.js' %}"></script>
<script src="{% static 'js/requests.js' %}"></script>
<script src="{% static 'js/sidebar.js' %}"></script>
</body>
</html>